# https://www.playframework.com/documentation/latest/Configuration

play.modules.enabled += "slinq.pg.play.module.SlinqModule"

slinq = {
  db = "world"
  user = ""
  password = ""
}

play.filters.enabled = []
